[package]
name = "dynamodb-query"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.5.0"
aws-sdk-dynamodb = "1.30.1"
csv = "1.3.0"
tokio = { version = "1.37.0", features = ["full"] }
futures = "0.3.30"
